apiVersion: v1
kind: Service
metadata:
  name: carworld-service
spec:
  type: NodePort
  selector:
    app: carworld
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
